declare module '*.svg';
declare module '*.json';
declare module '*.png';
declare module '*.jpg';
declare module '*.ico';
declare module '*.gif';
declare module '*.ttf';
declare module '*.woff';
declare module '*.woff2';